document.write('<table border=1 bordercolordark=#ffd068 bordercolorlight=#882200 cellpadding=0 cellspacing=0 width=770 align=center height=15>');
document.write('<tbody><tr align=center><td width=99 height=17>');
document.write('<font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=emg_lines.htm>Emergency Lines </a></font></b></font></td>');
document.write('<td width=59 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=helplines.htm>Help lines </a></font></b></font></td>');
document.write('<td width=92 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=entertainment.htm>Entertainment</a></font></b></font></td>');
document.write('<td width=80 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=travelguide.htm>Travel Guide </a></font></b></font></td>');
document.write('<td width=114 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=postinfo.htm>Postal Information </a></font></b></font></td>');
document.write('<td width=104 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=freelist.asp>Free listing Form</a></font></b></font></td>');
document.write('<td width=68 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=contactus.htm>Contact Us </a></font></b></font></td>');
document.write('<td width=51 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=search.htm>Search</a></font></b></font></td>');
document.write('<td width=68 height=17><font face=verdana><b><font color=#ff9966 size=1>');
document.write('<a class=a1 href=advertise.htm>Advertise </a></font></b></font></td>');
document.write('</tr></tbody></table>');