document.write('<table width=100% cellpadding=0 cellspacing=0 border=0>');
document.write('<tr bgcolor=ffcc00><td>&nbsp;</td><td class=text1 width=150 bgcolor=ffcc00 align=center><marquee><b>Thousands of Business Listings</b></marquee></td><td>&nbsp;</td>');
document.write('<td><table width=100% border=0 cellpadding=0 bgcolor=3366cc cellspacing=0>');
document.write('<tr align=center valign=middle class=mmenu_link>');
document.write('<td><a href=default.asp>Home</a></td>');
document.write('<td><a href=getlisting.asp>Get a Listing</a></td>');
document.write('<td><a href=help.asp>Help?</a></td>');
document.write('<td><a href=aboutus.asp>About Us</a></td>');
document.write('<td><a href=contact.asp>Contact Us</a></td>');
document.write('</tr></table></td></tr></table>');